#!/usr/bin/env bash

if [ "$1" = "" ]
then
 echo "Usage: $0 TRACK.it [DESTINATION]"
 echo "Splits impulse tracker file TRACK.it into stems and info in DESTINATION folder (default=./tracks/)."
else
  name="`basename ${1}`"
  if [ "${2}" = "" ]
  then
    dest="./tracks"
  else
    dest="${2}"
  fi
  dest="$dest/${name/.it/}"
  mkdir $dest
  it2pd $1 --info --stems "${dest}" > "${dest}/info.txt"
fi
